#! /bin/bash
python3 -m pip install -r requirements.txt

docker-compose up -d allure allure-ui

  python3 -m pytest Test/User/UserServiceTestCase.py --alluredir=allure-results
python3 -m pytest Test/User/UserRepositoryTestCase.py --alluredir=allure-results

python3 -m pytest Test/Item/ItemServiceTestCase.py --alluredir=allure-results
python3 -m pytest Test/Item/ItemRepositoryTestCase.py --alluredir=allure-results

python3 -m pytest Test/Look/LookServiceTestCase.py --alluredir=allure-results
python3 -m pytest Test/Look/LookRepositoryTestCase.py --alluredir=allure-results

python3 -m pytest Test/Wardrobe/WardrobeRepositoryTestCase.py --alluredir=allure-results
python3 -m pytest Test/Wardrobe/WardrobeServiceTestCase.py --alluredir=allure-results

python3 -m pytest Test/Invite/InviteServiceTestCase.py --alluredir=allure-results
python3 -m pytest Test/Invite/InviteRepositoryTestCase.py --alluredir=allure-results
